# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: DevTM

tagline: Development Tips & Memos

description: >-
  Travel, Tech, and Life — personal notes from Beijing.

url: "https://wakenhole-blog.github.io"

github:
  username: wakenhole-blog

social:
  name: wakenhole
  email: okhwan.lee@gmail.com
  links:
    - https://github.com/wakenhole-blog

webmaster_verifications:
  google: dwBwpiHYECKTEIPkkeC_R2wEXRBEw0OTqjzXhMjefng
  bing:

analytics:
  google:
    id: # fill in new GA4 ID

theme_mode: # [light | dark]

avatar: "/assets/img/images/avatar.png"

toc: true

comments:
  provider:

pwa:
  enabled: true
  cache:
    enabled: true

paginate: 10

baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /:year/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
